# Generated by Django 4.2.11 on 2024-03-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='name',
            field=models.CharField(default='Madrid', max_length=300),
            preserve_default=False,
        ),
    ]
