# Generated by Django 4.2.11 on 2024-03-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_stop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='stop',
            name='location_latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='location_longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stop',
            name='audio',
            field=models.FileField(upload_to='stops/audios/'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='image',
            field=models.ImageField(upload_to='stops/images/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='audio',
            field=models.FileField(upload_to='tours/audios/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=models.ImageField(upload_to='tours/photos/'),
        ),
    ]
